### ISSUE TITLE
The binding of variable user in directive user menu doesn't works and the popover too.

### ISSUE THREAD

**Issue by claudioviola** [ModusCreateOrg/ionic-seed#6]
Is it my fault?

**Comment by gvolkan** [comment]
it's not your fault. 
component was build with controllerAs syntax but there not added name, just add; 

```
bindings: {
   user: '='
},
controllerAs:'userMenu',
template: `
```

**Comment by dmackerman** [comment]
By default, the `component` syntax takes the name of the component and uses it as the `controllerAs` reference - so in this case `userMenu` should have been the default, which is strange.

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
