### ISSUE TITLE
Is it possible to receive in chrome dev tools in source panel the source file used in the project?

### ISSUE THREAD

**Issue by claudioviola** [ModusCreateOrg/ionic-seed#7]
Now I see only app.js, cordova.js and ng-inspector in the source panel
During develpment is very usefull to see the source file so we can receive in the console panel also the name of the source file where the console.log() is placed.
Probably is only a setting about source map? How can I set up it?

**Comment by claudioviola** [comment]
Resolved with devtool: 'eval-source-map'

**Comment by dmackerman** [comment]
Awesome, do you want to submit a PR?

**Comment by claudioviola** [comment]
Sorry...What is a PR? :)

**Comment by oikonomopo** [comment]
@claudioviola Pull request!

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
