### ISSUE TITLE
This project is stopped?

### ISSUE THREAD

**Issue by franck86** [ModusCreateOrg/ionic-seed#8]
Hi to all and thanks for your big work.
I have intension to use this work to start my project and i ask : this project is stopped?

Thanks for answers.

Good work ;)

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
