### ISSUE TITLE
If you wait until Webpack is done, and all gulp tasks are complete, the app will load. You shouldn't run into this error again.

### ISSUE THREAD

**Issue by richie50** [ModusCreateOrg/ionic-seed#9]
What exactly do you mean by this. And how do you ensure webpack will complete before all gulp task. Can you please elaborate

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
